-- MySQL Script generated by MySQL Workbench
-- Wed Oct 14 15:29:06 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema esiktu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema esiktu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `esiktu` DEFAULT CHARACTER SET utf8 ;
USE `esiktu` ;

-- -----------------------------------------------------
-- Table `esiktu`.`pegawai`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`pegawai` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`pegawai` (
  `NIP` VARCHAR(11) NOT NULL,
  `nama` VARCHAR(45) NOT NULL,
  `No_KTP` VARCHAR(20) NOT NULL,
  `TTL` DATE NOT NULL,
  `profesi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NIP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`user` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`user` (
  `id_user` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `hak_akses` VARCHAR(45) NOT NULL,
  `pegawai_NIP` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_pegawai_idx` (`pegawai_NIP` ASC) ,
  CONSTRAINT `fk_user_pegawai`
    FOREIGN KEY (`pegawai_NIP`)
    REFERENCES `esiktu`.`pegawai` (`NIP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`pangkat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`pangkat` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`pangkat` (
  `id_pangkat` INT NOT NULL,
  `pangkat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pangkat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`golongan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`golongan` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`golongan` (
  `id_golongan` INT NOT NULL,
  `golongan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_golongan`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`pendidikan_formal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`pendidikan_formal` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`pendidikan_formal` (
  `id_profesi_formal` INT NULL,
  `pendidikan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesi_formal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`pengalaman_kerja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`pengalaman_kerja` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`pengalaman_kerja` (
  `id_pengalaman_kerja` INT NULL,
  `pengalaman_kerja` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pengalaman_kerja`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`pendidikan_J_T`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`pendidikan_J_T` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`pendidikan_J_T` (
  `id_pendidikan_J_T` INT NOT NULL,
  `pelatihan` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_pendidikan_J_T`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`PNS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`PNS` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`PNS` (
  `id_PNS` VARCHAR(45) NOT NULL,
  `npwp` VARCHAR(45) NOT NULL,
  `pangkat` VARCHAR(45) NOT NULL,
  `no_kerpeg` VARCHAR(45) NOT NULL,
  `fk_id_pangkat` INT NOT NULL,
  `fk_id_golongan` INT NOT NULL,
  `fk_id_profesi_formal` INT NOT NULL,
  `fk_id_pengalaman_kerja` INT NOT NULL,
  `fk_id_pendidikan_J_T` INT NOT NULL,
  `fk_NIP` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`id_PNS`, `fk_id_pangkat`, `fk_id_golongan`, `fk_id_profesi_formal`, `fk_id_pengalaman_kerja`, `fk_id_pendidikan_J_T`, `fk_NIP`),
  INDEX `fk_PNS_pangkat1_idx` (`fk_id_pangkat` ASC) ,
  INDEX `fk_PNS_golongan1_idx` (`fk_id_golongan` ASC) ,
  INDEX `fk_PNS_pendidikan_formal1_idx` (`fk_id_profesi_formal` ASC) ,
  INDEX `fk_PNS_pengalaman_kerja1_idx` (`fk_id_pengalaman_kerja` ASC) ,
  INDEX `fk_PNS_pendidikan_J_T1_idx` (`fk_id_pendidikan_J_T` ASC) ,
  INDEX `fk_PNS_pegawai1_idx` (`fk_NIP` ASC) ,
  CONSTRAINT `fk_PNS_pangkat1`
    FOREIGN KEY (`fk_id_pangkat`)
    REFERENCES `esiktu`.`pangkat` (`id_pangkat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PNS_golongan1`
    FOREIGN KEY (`fk_id_golongan`)
    REFERENCES `esiktu`.`golongan` (`id_golongan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PNS_pendidikan_formal1`
    FOREIGN KEY (`fk_id_profesi_formal`)
    REFERENCES `esiktu`.`pendidikan_formal` (`id_profesi_formal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PNS_pengalaman_kerja1`
    FOREIGN KEY (`fk_id_pengalaman_kerja`)
    REFERENCES `esiktu`.`pengalaman_kerja` (`id_pengalaman_kerja`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PNS_pendidikan_J_T1`
    FOREIGN KEY (`fk_id_pendidikan_J_T`)
    REFERENCES `esiktu`.`pendidikan_J_T` (`id_pendidikan_J_T`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PNS_pegawai1`
    FOREIGN KEY (`fk_NIP`)
    REFERENCES `esiktu`.`pegawai` (`NIP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `esiktu`.`honorer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `esiktu`.`honorer` ;

CREATE TABLE IF NOT EXISTS `esiktu`.`honorer` (
  `id_honorer` INT NOT NULL,
  `jenis_ketenagaan` VARCHAR(45) NOT NULL,
  `profesi` VARCHAR(45) NOT NULL,
  `pegawai_NIP` VARCHAR(11) NOT NULL,
  `fk_id_PNS` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_honorer`),
  INDEX `fk_honorer_pegawai1_idx` (`pegawai_NIP` ASC) ,
  INDEX `fk_honorer_PNS1_idx` (`fk_id_PNS` ASC) ,
  CONSTRAINT `fk_honorer_pegawai1`
    FOREIGN KEY (`pegawai_NIP`)
    REFERENCES `esiktu`.`pegawai` (`NIP`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_honorer_PNS1`
    FOREIGN KEY (`fk_id_PNS`)
    REFERENCES `esiktu`.`PNS` (`id_PNS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
